### Generated by rprotoc. DO NOT EDIT!
### <proto file: servermessage.proto>
# option optimize_for = SPEED;
# 
# enum SERVER_MSG_ID
# {
# 	ID_S2S_REQUEST_REGISTER_SERVER		= 0x0101;			// 向服务器注册
# 	ID_S2S_RESPONSE_REGISTER_SERVER		= 0x0102;			// 向服务器注册的回复
# };
# 
# // ID_S2S_REQUEST_REGISTER_SERVER
# message CMessageRegisterServerRequest
# {
# 	optional string IPAddress	= 1;	// 对外网的IP地址
# 	optional uint32 Port		= 2;	// 对外网的端口
# };
# 
# // ID_S2S_RESPONSE_REGISTER_SERVER 
# message CMessageRegisterServerResponse
# {
# 
# };

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

::Protobuf::OPTIONS[:"optimize_for"] = :SPEED
class SERVER_MSG_ID < ::Protobuf::Enum
  defined_in __FILE__
  ID_S2S_REQUEST_REGISTER_SERVER = value(:ID_S2S_REQUEST_REGISTER_SERVER, 257)
  ID_S2S_RESPONSE_REGISTER_SERVER = value(:ID_S2S_RESPONSE_REGISTER_SERVER, 258)
end
class CMessageRegisterServerRequest < ::Protobuf::Message
  defined_in __FILE__
  optional :string, :IPAddress, 1
  optional :uint32, :Port, 2
end
class CMessageRegisterServerResponse < ::Protobuf::Message
  defined_in __FILE__
end